name: Deploy SaveConnects Backend

on:
  push:
    branches:
      - staging
      - develop-qa
      - master

jobs:
  deploy_qa:
    if: github.ref == 'refs/heads/develop-qa'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect with VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mkdir -p /home/tishan/apps/save-connects/backend
            cd /home/tishan/apps/save-connects/backend

            if [ -d ".git" ]; then
              git reset --hard HEAD
              git pull origin develop-qa
            else
              git clone -b develop-qa https://github.com/HashBaze/SaveConnects-BE.git .
            fi

            npm install --force
            npm run build

            pid=$(pm2 pid "save-connects backend" 2>/dev/null)
            if [ -n "$pid" ]; then
              echo "Reloading application"
              pm2 reload "save-connects backend"
              pm2 save
            else
              echo "New application"
              pm2 start npm --name "save-connects backend" -- start
              pm2 startup
              pm2 save
            fi
